Diagnostics:
  ClangTidy:
    Add: ["*"] #添加全部特性
    Remove: #根据自己的需求，移除不需要的特性
      [
        abseil*, #可以使用通配符匹配
        fuchsia*,
        llvmlib*,
        zircon*,
        altera*,
        performance-no-int-to-ptr,
        cppcoreguidelines-avoid-magic-numbers,
        readability-magic-numbers,
        bugprone-easily-swappable-parameters,
        hicpp-signed-bitwise,
        readability-braces-around-statements,
        hicpp-braces-around-statements,
        cppcoreguidelines-init-variables,
        readability-identifier-length,
        # hicpp-avoid-c-arrays,
        misc-unused-parameters,
      ]
CompileFlags:
  Remove: [-mthumb-interwork,-Wunsequenced]
  Add: [-isystem, "/usr/include",-ferror-limit=0]
Index:
  Background: Build
# Checks: '-*,clang-analyzer-*,-cppcoreguidelines-avoid-magic-numbers'